Fix fatal errors with removal of -Wincompatible-pointer-types
:Release Notes:
Fix fatal errors with removal of -Wincompatible-pointer-types

:Detailed Notes:
Fixed below build errors for luna-prefs component
http://gecko.lge.com:8000/Errors/Details/821703
luna-prefs/3.0.0-17/git/luna-prefs-service/accesschecker.c:39:39: error
: initialization of 'LSMessage *' from incompatible pointer type
'LSMessage **' [-Wincompatible-pointer-types]
luna-prefs/3.0.0-17/git/luna-prefs-service/accesschecker.c:85:24: error
: assignment to 'LSMessage **' from incompatible pointer type
'LSMessage *' [-Wincompatible-pointer-types]
luna-prefs/3.0.0-17/git/luna-prefs-service/main.c:487:48: error:
passing argument 4 of 'checkAccess' from incompatible pointer type
[-Wincompatible-pointer-types]
luna-prefs/3.0.0-17/git/luna-prefs-service/main.c:766:48: error:
passing argument 4 of 'checkAccess' from incompatible pointer type
[-Wincompatible-pointer-types]
luna-prefs/3.0.0-17/git/luna-prefs-service/main.c:959:48: error:
passing argument 4 of 'checkAccess' from incompatible pointer type
[-Wincompatible-pointer-types]
luna-prefs/3.0.0-17/git/luna-prefs-service/main.c:1072:49: error:
passing argument 4 of 'checkAccess' from incompatible pointer type
[-Wincompatible-pointer-types]

:Testing Performed:
Locally Tested.

:QA Notes:
N/A

:Issues Addressed:
[WRR-1657] Remove "-Wno-error=incompatible-pointer-types" flag and
           prepare changes

Change-Id: Iadfc43495bd308243444e8a981d5dfd8fa7171d8